// FETCH USER DATA

export const FETCH_TODOS_DATA_INIT = "FETCH_TODOS_DATA_INIT";
export const FETCH_TODOS_DATA_SUCCESS = "FETCH_TODOS_DATA_SUCCESS";
export const FETCH_TODOS_DATA_FAILURE = "FETCH_TODOS_DATA_FAILURE";
